### ISSUE TITLE
Race conditions

### ISSUE THREAD

**Issue by yelouafi** [sotojuan/saga-login-flow#1]
Hi,

In this line of code

https://github.com/sotojuan/saga-login-flow/blob/master/app/sagas/index.js#L58

You need to account for concurrent actions: If a `LOGOUT` action occurs while `authorize` is still in progress; `logout` will first will set auth to false. But when the pending authorize terminates it'll set auth to true again overriding the effects of `logout`. You may either cancel the pending authorize when a `LOGOUT` occurs or better merge the 2 flows using `race`. For example

```js
export function * loginFlow () {
  while (true) {
    let request = yield take(LOGIN_REQUEST)
    let {username, password} = request.data

    // if LOGOUT wins, it'll cancel the pending authorize call
    const winner = yield race({
      auth: call(authorize, username, password, false),
      logout: take(LOGOUT)
    })
    
    if(winner.auth) {
      yield put({type: SET_AUTH, newAuthState: true})
      yield put({type: CHANGE_FORM, newFormState: {username: '', password: ''}})
      forwardTo('/dashboard')
    } else {
      yield put({type: SET_AUTH, newAuthState: false})
      yield call(logout)
      forwardTo('/')
    }
  }
}
``` 

Here

https://github.com/sotojuan/saga-login-flow/blob/master/app/sagas/index.js#L33

I think `authorize` should handle its error itself

**Comment by sotojuan** [comment]
Hey, sorry for the late reply—school and graduation = busy. Got the `race` working but unsure what you mean by "`authorize` should handle its error itself"—if the `catch` in `authorize` looks like this:

```js
yield put({type: REQUEST_ERROR, error: error.message})
```

Then the page still moves to the dashboard even when the user did not log in because of a bad password or username. I guess I need to cancel the `loginFlow` task or something, but not sure from where.

**Comment by sotojuan** [comment]
Think I fixed it so closing—let me know if it looks good.
